# Generated by Django 5.0.4 on 2024-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
