# Generated by Django 5.0.4 on 2024-05-01 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_track_duration_alter_track_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="order",
        ),
    ]
