# Generated by Django 5.0.4 on 2024-05-02 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_album_tracks_alter_track_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="tracks",
        ),
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="catalog.artist",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="catalog.album",
            ),
        ),
    ]
